server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode\=true&amp;characterEncoding\=UTF-8
    username: root
    password: 141500
    driver-class-name: com.mysql.jdbc.Driver

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
    timeout: 0ms
  application:
    name: spring-boot
mybatis:
  mapper-locations: classpath:mappers/*.xml


