server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode\=true&amp;characterEncoding\=UTF-8
    username: root
    password: 141500
    driver-class-name: com.mysql.jdbc.Driver
